# Application
spring.application.name=LAM

# server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=lammanager
spring.datasource.username=lam
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# mybatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true